Repository multi-coop/multi-site-contents, pull requests merged in 2022-03, with the labels that each got.

#22 Ajout de la page jailbreak-devient-multi
  texts/blog/blog-data.md
  texts/blog/posts/jailbreak-devient-multi-fr.md
Labels: enhancement

#25 Update jailbreak-devient-multi-fr.md
  texts/blog/posts/jailbreak-devient-multi-fr.md
Labels: enhancement

#17 add shuffle to team data
  texts/team/team-data.md
Labels: enhancement, edito

#24 add thomas email + shiny tag for Pierre
  texts/team/people/Pierre-Camilleri.md
  texts/team/people/Thomas-Brosset.md
Labels: enhancement, edito

#27 Update jailbreak-devient-multi-fr.md
  texts/blog/posts/jailbreak-devient-multi-fr.md
Labels: edito

#30 add Open Heroines in network section
  texts/network/images/open-heroines.png
  texts/network/items/open-heroines.md
  texts/network/network-data.md
Labels: enhancement, edito

#29 Update article-Gregoire-Intermittents_du_spectacle.md
  texts/ressources/items/article-Gregoire-Intermittents_du_spectacle.md
Labels: enhancement, edito

#28 Update footer.md
  config/footer.md
Labels: enhancement, edito

#33 Add favicon multi
  config/global.md
  images/logos/favicon_multi.ico
  images/logos/icon_multi.png
Labels: enhancement

#31 add IPCC report on climate change
  texts/ressources/images/IPCC-GIEC.png
  texts/ressources/items/report-GIEC.md
  texts/ressources/ressources-data.md
Labels: enhancement, edito

#38 Add new ressources
  texts/ressources/images/Value_in_the_commons_economy.png
  texts/ressources/images/governing_knowledge_commons.jpeg
  texts/ressources/items/book-Frischmann-Madison-Strandburg-governing_knowledge_commons.md
  texts/ressources/items/report-Bauwens-value_in_the_commons_economy.md
  texts/ressources/ressources-data.md
Labels: edito

#36 Add matrix
  config/footer.md
  config/routes.md
Labels: enhancement, edito

#40 Update Gitlab URL
  config/footer.md
Labels: bug, edito

#41 add fabmob to network section
  texts/network/images/fabmob_cmjn6.svg
  texts/network/images/logo-ADEME-resilience.png
  texts/network/items/ademe-resilience.md
  texts/network/items/fabmob.md
  texts/network/network-data.md
  texts/ressources/ressources-data.md
Labels: enhancement, edito
