Repository multi-coop/multi-site-contents, pull requests merged in 2022-11, with the labels that each got.

#63 comment old job adds
  texts/jobs/jobs-data.md
Labels: jobs

#60 renaming gitribute into Datami
  images/references/datami/datami-landing.png
  images/references/datami/explowiki-preview-01.png
  images/references/datami/gitfile-csv-preview-01.png
  images/references/datami/gitfile-json-preview-01.png
  images/references/datami/gitfile-md-preview-01.png
  images/references/datami/multifiles-preview-01.png
  texts/references/products-data.md
  texts/references/projects/datami.md
  texts/references/references-data.md
Labels: edito

#56 add matomo settings in config file
  config/global.md
Labels: enhancement

#53 Add clients logos
  config/global.md
  config/routes.md
  images/clients/ademe-logo.png
  images/clients/anct-logo.png
  images/clients/conumm-logo.png
  images/clients/decider-ensemble-logo.jpg
  images/clients/dept-doubs-logo.jpg
  images/clients/dinum-logo.png
  images/clients/epa-senart-logo.png
  images/clients/fabmob-logo.png
  images/clients/francilin-logo.jpg
  images/clients/mednum-bfc-logo.png
  images/clients/mednum-logo.jpg
  images/clients/min-mer-logo.png
  images/clients/mte-logo.png
  images/clients/odf-logo.svg
  images/clients/ping-logo.png
  images/clients/rhinocc-logo.jpg
  texts/landing/landing-clients-intro-en.md
  texts/landing/landing-clients-intro-fr.md
  texts/landing/landing-clients-logos.md
Labels: enhancement, edito
